### ISSUE TITLE
M1 install error.

### ISSUE THREAD

**Issue by Cat7373** [RfidResearchGroup/homebrew-proxmark3#56]
```
brew upgrade
==> Upgrading 1 outdated package:
rfidresearchgroup/proxmark3/proxmark3 4.19552 -> 4.20142
==> Fetching rfidresearchgroup/proxmark3/proxmark3
==> Downloading https://github.com/RfidResearchGroup/proxmark3/archive/refs/tags/v4.20142.tar.gz
Already downloaded: /Users/cat73/Library/Caches/Homebrew/downloads/06ba2dd50c7ffc9ffa1d8cf6f738ee5f9ecf0ded9eaa5c591dc78d222a76aa54--proxmark3-4.20142.tar.gz
==> Upgrading rfidresearchgroup/proxmark3/proxmark3
  4.19552 -> 4.20142 
==> make clean
==> make all BREW_PREFIX=/opt/homebrew PLATFORM=PM3RDV4 SKIPQT=1
==> make install PREFIX=/opt/homebrew/Cellar/proxmark3/4.20142 BREW_PREFIX=/opt/homebrew PLATFORM=PM3RDV4 SKIPQT=1
Last 15 lines from /Users/cat73/Library/Logs/Homebrew/proxmark3/03.make:
[*] MAKE deps/id48/libid48.a
make[2]: Nothing to be done for `all'.
[*] MAKE obj/libmbedtls.a
make[2]: Nothing to be done for `all'.
[*] MAKE deps/reveng/libreveng.a
make[2]: Nothing to be done for `all'.
[*] MAKE deps/tinycbor/tinycbor.a
make[2]: Nothing to be done for `all'.
[*] MAKE deps/whereami/libwhereami.a
make[2]: Nothing to be done for `all'.
[@] Installing client to /opt/homebrew/Cellar/proxmark3/4.20142...
# hack ahead: inject installation path into pm3_resources.py
sed: 1: "pyscripts/pm3_resources.py": extra characters at the end of p command
make[1]: *** [install] Error 1
make: *** [client/install] Error 2

If reporting this issue please do so at (not Homebrew/* repositories):
  https://github.com/rfidresearchgroup/homebrew-proxmark3/issues
```

<img width="237" alt="Image" src="https://github.com/user-attachments/assets/2638e6a5-f711-46df-85af-4ac41ffd15d6" />

**Comment by djerfy** [comment]
Hi, same error with Apple M3 Max

**Comment by prplpwny** [comment]
I'm running into the same issue as described above on M3 silicone. The error is most likely due to "make install" using a "sed -i" command that is specific to GNU sed, which will fail on BSD sed which requires a different syntax.

In BSD sed, -i requires a mandatory backup extension argument (even if it's empty). It looks like that is missing, causing this issue.

Repro:

```
% echo "hello world" > test.txt

% sed -i 's/world/macos/' test.txt

sed: 1: "test.txt": undefined label 'est.txt'

% cat test.txt                 
hello world

% sed -i ''  's/world/macos/' test.txt

% cat test.txt 
hello macos
```

In a nutshell, adding an empty `''` to sed should fix the issue for BSD-style systems, without breaking GNU sed.

**Comment by aruznieto** [comment]
Same for me

**Comment by sickboy2468** [comment]
also me

**Comment by Cat7373** [comment]
> The issue has already been resolved in the master (head) branch.

I still can't install it here, maybe brew hasn't been updated yet

```
brew upgrade
==> Downloading https://formulae.brew.sh/api/formula.jws.json
==> Upgrading 1 outdated package:
rfidresearchgroup/proxmark3/proxmark3 4.19552 -> 4.20142
==> Fetching rfidresearchgroup/proxmark3/proxmark3
==> Downloading https://github.com/RfidResearchGroup/proxmark3/archive/refs/tags/v4.20142.tar.gz
Already downloaded: /Users/cat73/Library/Caches/Homebrew/downloads/06ba2dd50c7ffc9ffa1d8cf6f738ee5f9ecf0ded9eaa5c591dc78d222a76aa54--proxmark3-4.20142.tar.gz
==> Upgrading rfidresearchgroup/proxmark3/proxmark3
  4.19552 -> 4.20142 
==> make clean
==> make all BREW_PREFIX=/opt/homebrew PLATFORM=PM3RDV4 SKIPQT=1
==> make install PREFIX=/opt/homebrew/Cellar/proxmark3/4.20142 BREW_PREFIX=/opt/homebrew PLATFORM=PM3RDV4 SKIPQT=1
Last 15 lines from /Users/cat73/Library/Logs/Homebrew/proxmark3/03.make:
[*] MAKE deps/id48/libid48.a
make[2]: Nothing to be done for `all'.
[*] MAKE obj/libmbedtls.a
make[2]: Nothing to be done for `all'.
[*] MAKE deps/reveng/libreveng.a
make[2]: Nothing to be done for `all'.
[*] MAKE deps/tinycbor/tinycbor.a
make[2]: Nothing to be done for `all'.
[*] MAKE deps/whereami/libwhereami.a
make[2]: Nothing to be done for `all'.
[@] Installing client to /opt/homebrew/Cellar/proxmark3/4.20142...
# hack ahead: inject installation path into pm3_resources.py
sed: 1: "pyscripts/pm3_resources.py": extra characters at the end of p command
make[1]: *** [install] Error 1
make: *** [client/install] Error 2

If reporting this issue please do so at (not Homebrew/* repositories):
  https://github.com/rfidresearchgroup/homebrew-proxmark3/issues
```

**Comment by wesbos** [comment]
Seems the homebrew is still out of date, running `brew install --HEAD --with-generic proxmark3` installs the latest from github.

**Comment by Cat7373** [comment]
Hmm, I want to wait for the brew install proxmox3 update, after all, most users should use this version

**Comment by drweber** [comment]
Hey. Please look on my answer [here](https://github.com/RfidResearchGroup/homebrew-proxmark3/issues/54#issuecomment-2868900336). in short: version from HEAD works for my M2
